server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ar?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**.xml


